# Generated by Django 3.0.8 on 2020-07-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_auto_20200730_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDB_File',
        ),
    ]
